### ISSUE TITLE
Crash without any information

### ISSUE THREAD

**Issue by mikaoP** [nickgillian/grt#126]
Hi, my program ends crashing when i train the pipeline with this trainingData and ANBC
https://transfer.sh/gaR2j/gestures.grt
However, with a similar file but using one class it works...

I'm using Windows 10 with visual studio 2015

**Comment by mikaoP** [comment]
I have done some debug and it crashes throwing `excepción de Microsoft C++: std::bad_alloc en la ubicación de la memoria 0x008FBD48`. It seems GRT tries to have all training data information on memory and when it has not enought the program dies

**Comment by mikaoP** [comment]
I see. The problem was the huge size of the file

**Comment by nickgillian** [comment]
How big was the file?
