### ISSUE TITLE
OSC in GUI bug

### ISSUE THREAD

**Issue by cyberluke** [nickgillian/grt#20]
When using just classification mode, the Processing example works fine (keys 'r', '[', ']'). But when switching to timeseries mode, the OSC messages are received, but GUI is not updated and new samples are not saved, therefore it's impossible to perform training on dataset in timeseries mode.

**Comment by nickgillian** [comment]
Thanks for flagging this. I've updated the GUI, but haven't had time to update the GUI's backend so it can be controlled by the supporting examples (like for Processing) for the new modes (timeseries classification mode and clustering mode).  I'll add this soon and get everything synced up.

**Comment by cyberluke** [comment]
Yes, please :-) I'd like to use it today. Actually I thought I will have to fix it myself. I know you're busy, but if you could just tell me where to look or commit the current work into some testing branch, I would continue on it.

**Comment by cyberluke** [comment]
Problem solved. I was using Version: 1.0 of Processing example (from wiki). In GIT, there is version 1.2 in extensions folder and that is working :-)
