### ISSUE TITLE
Issue with the GUI not saving training data

### ISSUE THREAD

**Issue by narner** [nickgillian/grt#39]
Hi Nick, 

Whenever I run the Processing Classification Example / GRT-GUI following the steps in the [tutorial](http://www.nickgillian.com/wiki/pmwiki.php/GRT/GUIProcessing), I an error of "WARNING: Failed to save training data saved to file" appears in the Info Text box in the GUI. 

Additionally, when I click on "Save" in the Data Manager tab, the dialog allows me to click on the "save" button, but when I click on "Load", no file is shown. 

I'm running OS X 10.11.1. Thank you!

**Comment by nuralhuda** [comment]
Same problem

**Comment by nuralhuda** [comment]
I used an older GRT: http://www.nickgillian.com/archive/wiki/grt/download/gui/GRT_V0.1_15.zip this worked. But I am not sure if it has support for time series data, which is what I want.

**Comment by nickgillian** [comment]
Strange, these issues might be related to some updates on 10.11.1 (as the GUI was compiled on a slightly older version of OSX).

I'll try making a new build for OS X 10.11.1 and see if this resolves the problem.

**Comment by narner** [comment]
This seems to be working fine for me now!

**Comment by narner** [comment]
In case anyone else experiences this issue, try these two things:

1) Make sure you're saving your file with either a .csv or a .grt extension
2) Make sure you're saving your file to a location where you have write privileges.
