### ISSUE TITLE
arm architecture

### ISSUE THREAD

**Issue by Squall87** [nickgillian/grt#52]
Hi there

Thank you for this library: it is being so usefull. I was wondering: basing on the informations you released the library has been tested and build for linux, osx and windows, is there any plan to make it work for arm as well?

Thanks a lot

**Comment by narner** [comment]
@Squall87 did you end up figuring out the settings for arm devices? I was planning on looking at using the GRT with iOS projects, but haven't had the chance to dig deeply into it yet.

**Comment by Squall87** [comment]
I did not end up completely: I have only build the library for armhf (no problems) but haven't tested it so far. The same for OSX. I'll post results as soon as I test it
