### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by JairoJs** [nickgillian/grt#53]
Hello Nick.

I am getting started with you GRT but the link to the documentation seems to be broken, I could downloaded navigating through the directories of your web but Im not sure if that is the Latest Version. Here is the URL Ive downloaded from http://www.nickgillian.com/archive/wiki/grt/doxygen/04-03-15.zip

**Comment by nickgillian** [comment]
Hi JarioJS,

I've been having some issues with my site hosting lately, so this has broken a few things (such as my main website, the GRT documentation and forum).

I've just uploaded a new temporary site while I improve things, so you can find the latest build of the documentation here: http://nickgillian.com/grt

If you follow the links on that site to the wiki, you can find a large number of examples and details about the various GRT algorithms: http://nickgillian.com/wiki

I hope this helps you get started.
