### ISSUE TITLE
how to use GRT in android project?

### ISSUE THREAD

**Issue by leekingly** [nickgillian/grt#65]
Hi,nick
 I have seen the jni folder in your GRT project,does it means it can support in java?and how can I complie the source?can you provide a detailed introduction？？

**Comment by nickgillian** [comment]
Hi leekingly,

You should be able to find instructions for using the GRT in android on this [blog post](http://hollyhook.de/wp/grt-for-android/).  I hope this helps!

**Comment by frankbolton** [comment]
hi @nickgillian 
did you mirror the blogposts from hollyhook.de? The website is down
