### ISSUE TITLE
Tiny issue in ClassificationData::spiltDataIntoKFolds()

### ISSUE THREAD

**Issue by daniellocust** [nickgillian/grt#80]
[problem]
At the start of the function:
    //K can not be zero
    if( K > totalNumSamples ){
        errorLog << "spiltDataIntoKFolds(const UINT K,const bool useStratifiedSampling) - K can not be zero!" << std::endl;
        return false;
    }
is to compare K and zero, but here is totalNumSamples.

[Suggestion]
change the totalNumSamples to 0 to fix the problem.

**Comment by nickgillian** [comment]
Good catch! I've pushed a fix to this to the dev branch and will merge this into the master branch this weekend with some other updates.
