### ISSUE TITLE
what's the differenece between continuousHMM and discreateHMM

### ISSUE THREAD

**Issue by daniellocust** [nickgillian/grt#93]
Hello, Nickgillian!

  I'm studying the HMM, and read the code of continuousHiddenmarkovmodel.cpp. In the train_(...) function, i didn't find the code to implement Baum-Welch algorithm, but the algorithm is implemented in DiscreteHiddenMarkovModel.cpp. So, i wanna to know what difference is between this two kind of algorithm, and why continuousHMM need not to implement Baum-Welch algorithm? Thanks!

**Comment by nickgillian** [comment]
Hi daniellocust,

Your analysis of the two HMM algorithms (discrete and continuous) is correct.  The two algorithms use very different algorithms:

* the [discrete HMM algorithm](https://github.com/nickgillian/grt/blob/master/examples/ClassificationModulesExamples/HMMDiscreteExample/HMMDiscreteExample.cpp) uses the classic HMM algorithm, part of which is the Baum Welch algorithm for training the state transition and obverstation matrices, see my [thesis](http://www.nickgillian.com/papers/NicholasGillianThesisElectronic.pdf#page=106) for more info on this.
* the [continuous HMM](https://github.com/nickgillian/grt/blob/master/examples/ClassificationModulesExamples/HMMContinuousExample/HMMContinuousExample.cpp) algorithm is roughly based on a version of [this HMM algorithm](http://articles.ircam.fr/textes/Bevilacqua09b/index.pdf) by Bevilacqua et. al.  If you read [this paper](http://articles.ircam.fr/textes/Bevilacqua09b/index.pdf) you should see the main algorithm behind the continuous HMM.

At some point, I would like to revisit both algorithms and improve them, as neither implementation is optimal, so if you're interested in helping to improve the core algorithms behind either/both then let me know.

**Comment by daniellocust** [comment]
Hi Nickgillian, 
   Thank you very much!
