### ISSUE TITLE
Face exception when running Synapse.exe in Windows 8.

### ISSUE THREAD

**Issue by jingyi2811** [nickgillian/grt#96]
Hi Nick and others,

I try to use grt with kinect. And I follow the written instructions to install Synapse and Open Framework.

However, I face exception when running the Synapse.exe file. (See the attachment below).

![untitled](https://cloud.githubusercontent.com/assets/7101806/18842510/cef7ea40-8447-11e6-8afb-97d27ece3161.png)

I believe my open ni and nite path is correct and I did run the file with admin priviledge but it doesn't help either.

For your information, I am using Windows 8. I wonder is it better to use Windows 7 instead?

I understand Mac is a more suitable OS to use Synapse. But, I hope I can run it in Windows.

Regards,
Jimmy

**Comment by leekingly** [comment]
Hi,I remember nick says you'd betweer use Synapse on windows7 instead

**Comment by jingyi2811** [comment]
Hi, 

I think you are right. It was mentioned in the these lines

SYNAPSE for Kinect

Update: There’s some newer Kinect hardware out there, “Kinect for Windows”.  This hardware is slightly different, and doesn’t work with Synapse.  Be careful when purchasing, Synapse only supports “Kinect for Xbox”. Update to the update: There appears to also be newer “Kinect for Xbox” hardware out there. Model 1414 Kinects work with Synapse, but I’m getting reports that the newer 1473 models do not work. **Update the third: Synapse doesn’t work on Windows 8, sorry.**

Regards,
Jimmy
